# distribuicao/urls.py

# distribuicao/urls.py
URLS_DFE = {
    "AC": "https://dfe.svrs.rs.gov.br/ws/NFeDistribuicaoDFe/NFeDistribuicaoDFe.asmx",
    "AL": "https://dfe.svrs.rs.gov.br/ws/NFeDistribuicaoDFe/NFeDistribuicaoDFe.asmx",
    "AM": "https://dfe.svrs.rs.gov.br/ws/NFeDistribuicaoDFe/NFeDistribuicaoDFe.asmx",
    "AP": "https://dfe.svrs.rs.gov.br/ws/NFeDistribuicaoDFe/NFeDistribuicaoDFe.asmx",
    "BA": "https://dfe.svrs.rs.gov.br/ws/NFeDistribuicaoDFe/NFeDistribuicaoDFe.asmx",
    "CE": "https://dfe.svrs.rs.gov.br/ws/NFeDistribuicaoDFe/NFeDistribuicaoDFe.asmx",  # ← CORRIGIDO
    "DF": "https://dfe.svrs.rs.gov.br/ws/NFeDistribuicaoDFe/NFeDistribuicaoDFe.asmx",
    "ES": "https://dfe.svrs.rs.gov.br/ws/NFeDistribuicaoDFe/NFeDistribuicaoDFe.asmx",
    "MA": "https://dfe.svrs.rs.gov.br/ws/NFeDistribuicaoDFe/NFeDistribuicaoDFe.asmx",
    "MS": "https://dfe.svrs.rs.gov.br/ws/NFeDistribuicaoDFe/NFeDistribuicaoDFe.asmx",
    "MT": "https://dfe.svrs.rs.gov.br/ws/NFeDistribuicaoDFe/NFeDistribuicaoDFe.asmx",
    "PA": "https://dfe.svrs.rs.gov.br/ws/NFeDistribuicaoDFe/NFeDistribuicaoDFe.asmx",
    "PB": "https://dfe.svrs.rs.gov.br/ws/NFeDistribuicaoDFe/NFeDistribuicaoDFe.asmx",
    "PE": "https://dfe.svrs.rs.gov.br/ws/NFeDistribuicaoDFe/NFeDistribuicaoDFe.asmx",
    "PI": "https://dfe.svrs.rs.gov.br/ws/NFeDistribuicaoDFe/NFeDistribuicaoDFe.asmx",
    "RJ": "https://dfe.svrs.rs.gov.br/ws/NFeDistribuicaoDFe/NFeDistribuicaoDFe.asmx",
    "RN": "https://dfe.svrs.rs.gov.br/ws/NFeDistribuicaoDFe/NFeDistribuicaoDFe.asmx",
    "RO": "https://dfe.svrs.rs.gov.br/ws/NFeDistribuicaoDFe/NFeDistribuicaoDFe.asmx",
    "RR": "https://dfe.svrs.rs.gov.br/ws/NFeDistribuicaoDFe/NFeDistribuicaoDFe.asmx",
    "SC": "https://dfe.svrs.rs.gov.br/ws/NFeDistribuicaoDFe/NFeDistribuicaoDFe.asmx",
    "SE": "https://dfe.svrs.rs.gov.br/ws/NFeDistribuicaoDFe/NFeDistribuicaoDFe.asmx",
    "TO": "https://dfe.svrs.rs.gov.br/ws/NFeDistribuicaoDFe/NFeDistribuicaoDFe.asmx",
    # Demais UFs mantêm seus endpoints próprios
    "GO": "https://dfe.go.gov.br/nfe/distribuicaoDFe/nfeDistDFeInteresse.asmx",
    "MG": "https://dfe.fazenda.mg.gov.br/nfe2/services/NFeDistribuicaoDFe/NFeDistribuicaoDFe.asmx",
    "PR": "https://dfe.sefa.pr.gov.br/nfe/NFeDistribuicaoDFe/NFeDistribuicaoDFe.asmx",
    "RS": "https://dfe.sefaz.rs.gov.br/ws/nfe/NFeDistribuicaoDFe/NFeDistribuicaoDFe.asmx",
    "SP": "https://nfe.fazenda.sp.gov.br/ws/nfedistribuicaodfe.asmx",
}
UF_PARA_CODIGO = {
    "11": "RO",
    "12": "AC",
    "13": "AM",
    "14": "RR",
    "15": "PA",
    "16": "AP",
    "17": "TO",
    "21": "MA",
    "22": "PI",
    "23": "CE",
    "24": "RN",
    "25": "PB",
    "26": "PE",
    "27": "AL",
    "28": "SE",
    "29": "BA",
    "31": "MG",
    "32": "ES",
    "33": "RJ",
    "35": "SP",
    "41": "PR",
    "42": "SC",
    "43": "RS",
    "50": "MS",
    "51": "MT",
    "52": "GO",
    "53": "DF",
}
